### ISSUE TITLE
CoPRA: Show KM line in Cost Item when Sales or Purchase project had KM = Yes

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#16]
If   Purchase Project OR Sales Project has KM on Yes, then allow line for KM on   Cost item (currently the application only looks at Sales Project).

**Comment by davedx** [comment]
The cost items are only related to a sales project, the purchase and sales projects aren't really related so I don't know how we can do this. Maybe I'm missing something?

**Comment by laradg** [comment]
I understand. We did not consider this when we linked the cost item to the sales project only. Perhaps the best way would be to include this question in the Sales project? 

So in AVMT fields:
- KM reimbursed Y/N
- KM deductable YN
- Expenses reimbursed Y/N

In case either of the KM fields is Y, then show the line for KM in CoPRA. The KM for the Purchase project does not have to be shown in that case in the AVMT. Would that work?
