### ISSUE TITLE
AVMT: missing field Magno IT entity

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#19]
Dropdown field with options MIR and MIP.

//Lara will write a script to create the column in the SQL table and to add the correct value to existing projects.

**Comment by laradg** [comment]
Script is easypeasy:
```
ALTER TABLE AVProject ADD MagnoEntity nvarchar(max) NULL

GO

UPDATE AVProject SET MagnoEntity = 'MIR'
```
(no 'MIP' projects have been created yet)
**over to you maestro**

**Comment by davedx** [comment]
Added in Project Modal. I also added it to the table showing the list of projects for a professional.
