### ISSUE TITLE
AVMT: Add External Approver functionality

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#20]
For a Sales project, it should be possible to set an External approver, currently only Internal approver functionality is working.

- The dropdown to select an Approver should have a button to add a new Approver.
![image](https://user-images.githubusercontent.com/24442624/62944521-25234000-bddd-11e9-97c4-cf040ded0961.png)

Clicking button new approver should result in a popup with the following fields:
- Approver type (dropdown with values "Internal" or "External")
- Name (input)
- E-mail address (input)
In case Approver type was set to "External", ideally, when this popup is confirmed, an e-mail should be sent to the approver to announce their registration in CoPRA. The external approver should only receive this e-mail upon their first registration in CoPRA (e-mail content is available).

The user should not be able to save the **Sales** project without selecting an approver (internal or external). The selected approver does **not** need to receive e-mail confirmation of this action.

**Comment by davedx** [comment]
Done; I copied and amended the existing "Welcome to COPRA" email sent to new users and removed the login link from that mail.
