### ISSUE TITLE
CoPRA: Add External approver functionality

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#21]
This issue should be completed after issue #20 .

When a Cost Item is Submitted that has approver type "External approver", an e-mail should be sent to the e-mail address of the external approver. This e-mail should contain a unique link, that directs to a web page showing the content of that specific Cost item and buttons Reject, Approve and an input field to add a Remark.

**Comment by davedx** [comment]
Done. I also removed the 'Back' button and 'Logout' link for these users.
