### ISSUE TITLE
Link in Timesheet Submitted mails does not work

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#27]
The link in the following e-mail only works when I am logged in to CoPRA as a Magno Internal user, otherwise it only says "Loading".

COPRA: Timesheet Submitted 
Dear Magno Internal,
Jiri Kramer has submitted a new timesheet (05-08-2019 - 11-08-2019) for you to review.
Please use the following link to review the timesheet:
https://copra.magno-it.nl/?id=548&page=timesheet

**Comment by laradg** [comment]
Or sometimes: You don't have permission to access this timesheet.
Haven't been able to work out what triggers the difference. Usually it just says "Loading"

**Comment by davedx** [comment]
Aha yes it will only work if you are logged into the user who owns or can approve the timesheet unless it's a user who approves with an email. I'll try and improve the user experience...

**Comment by davedx** [comment]
I've made it redirect to login page if the user isn't authenticated.

We could also make it remember the URL the user tried to access and redirect them after successful login, but that's a bit more work so let's make a new issue if we want that.
