### ISSUE TITLE
CoPRA: Determine approver of timesheet upon submission timesheet

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#28]
Currently, the approver of a timesheet is set upon creation of the timesheet.
If the approver of a project changes after creation of the timesheet, then the new approver should automatically be able to see all Submitted timesheets and Approved timesheets of that project.
The new approver should also be able to Approve a newly Submitted timesheet.

**Comment by davedx** [comment]
If in AVM the approver for the project is changed, it now retroactively sets the approver for all timesheets for that project to the new approver.
