### ISSUE TITLE
Add "Internal" approver for all Magno admins

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#3]
Selecting the approver for a Sales project. 
From what I understood yesterday you wanted to create a User for every external approver, and I think that the intention is that you would be able to select the name of the external approver in the field Approver and the system will then automatically know that the approver is external and where to send e-mails etc.
With the "Internal" approver type, it was our intention that every admin user of Magno IT would be able to see and/or approve and reject all costs items of all professionals.
**Currently it shows Approver "Lara de Groot", but would it be possible to replace this by "Internal" which would cover for every Magno Admin user?**

**Comment by davedx** [comment]
Fixed.
