### ISSUE TITLE
Use e-mail address copra@magno-it.nl as sender of e-mails

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#37]
E-mail address copra@magno-it.nl has been created.
The website web.config uses the following details to e-mail, should be the same for copra:
```
<system.net>
    <mailSettings>
      <smtp>
        <network
             host="outbound.magno-it.nl"
             port="25"
             userName=""
             password="" />
      </smtp>
    </mailSettings>
  </system.net>
```

**Comment by davedx** [comment]
I made a new version that completely omits the "auth" block of the email config, maybe that will make it work, can we try again? :)
