### ISSUE TITLE
Table styling issues

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#39]
The tables are all one size, but either not wide enough, or columns should be arranged differently.

Example **Cost items to be processed**
![image](https://user-images.githubusercontent.com/24442624/63683101-c9ec4700-c7f9-11e9-8a07-79a00843d5fc.png)
- Column [Week number] could be more narrow (max 2 digits)
- Column [Worked could be more narrow (max "xx.xx")
- Header background exceeds table size
- Mouseover mackground exceeds table size

Example **Processed cost items**
![image](https://user-images.githubusercontent.com/24442624/63683227-1b94d180-c7fa-11e9-8135-eb9b9969eb41.png)
- Column [Week number] could be more narrow (max 2 digits)
- Column [Worked could be more narrow (max "xx.xx")
- Last column value exceeds table size
- Header background exceeds table size
- Mouseover mackground exceeds table size

**Comment by davedx** [comment]
Edit: Disregard :)

**Comment by davedx** [comment]
I actually removed the width setting for the table cells and let it size itself, I think it looks decent. What do you think? If it's okay I'll make another build :)
<img width="1017" alt="Screenshot 2019-08-26 at 13 03 03" src="https://user-images.githubusercontent.com/1479448/63686336-f0ae7b80-c801-11e9-9f3a-51e2d7ef68a8.png">

**Comment by davedx** [comment]
Hmm I just noticed in the screenshot that the columns are now diff widths for the same data items. I think I'll set the widths properly after all...

**Comment by laradg** [comment]
Tested OK, thank you!
