### ISSUE TITLE
Faulty validation on cut-off point

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#4]
When opening a Sales project (existing or new) by default the selected cut-off point is "Last Friday of the month", if that is correct (so I don't change it, but save the project, then it shows an error "Please select a cut-off type". If I first switch to "Last day of the month" and then back to "Last Friday of the month" it does save correctly.

**Comment by davedx** [comment]
Seems to have been fixed by work on the other validation issues. :)
