### ISSUE TITLE
Approver cannot see name of Candidate for Cost item tables

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#40]
For administrator the table looks like:
![image](https://user-images.githubusercontent.com/24442624/63694704-53f6d880-c817-11e9-9d5f-78f813312afe.png)

The Name column is not visible for an External approver (in any of the tables), can this please be added:
![image](https://user-images.githubusercontent.com/24442624/63694761-70931080-c817-11e9-95b3-4b47cee52338.png)

**Edit**: Same for when the cost item is opened. The administrator can see the name of the candidate, the external approver cannot.

**Comment by davedx** [comment]
Fixed the home page issue.

Regarding when you open the cost item: which name do you mean? The name in the navigation bar is the name of the logged in user, and the only other name I see is the approver?

**Comment by laradg** [comment]
Fixed!
