### ISSUE TITLE
AVMT: Add backup approvers to Sales project

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#44]
As per design below (italic is nice to have):
* For projects, support a list of approvers instead of a single one
  * There is one primary approver and the others are "backup"
  * UI should support setting anyone in the list to "Primary" (show "Are you sure?" prompt for this)
  * (Relationship is many-to-many so we need a join table)
* Anyone in the approvers list must be able to approve all existing and new CI’s related to this project
* ‘Approver backups’ have the same rights as the ‘Primary Approver’, but do not receive emails about submitted timesheets
* Whenever a project's approver list is updated, update the "primary approver" fields for all timesheets for the project (see COPRA issue)

![image](https://user-images.githubusercontent.com/24442624/65431892-7da51e80-de1a-11e9-8da1-37fdc6b803d2.png)

**Comment by laradg** [comment]
Changes for CoPRA corresponding to this issue described in issues #46 and #47.

**Comment by davedx** [comment]
Are you sure you only want one backup approver and won't need a list of approvers in the future? This might be a simpler way of solving this (a list of approvers). The timesheet system I use for Carnext has a list (I can actually assign my timesheet to any approver in the list, and I think they then get the notification email).

**Comment by laradg** [comment]
A list would work, but the professional should not be able to assign an
approver to the timesheet himself, just us in the AVM tool.
If we could assign more than 2 approvers that would be very useful.
Thanks! xxx

**Comment by laradg** [comment]
Tested this is working perfectly!
