### ISSUE TITLE
COPRA: Loading

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#45]
After login COPRA responds very quickly with showing the relevant tables.
With the increasing amount of data, the loading of data becomes noticeable already.
Consider:
•	Displaying an ‘hourglass’ to inform the user that loading is in progress.
•	Loading and displaying the content of tables [Processed cost items] and [Did not work cost items] on request only, by inserting a ‘request’ button to the table header.
•	Displaying data ‘table-by-table’ from top to bottom in order to ‘reduce’ response time.

**Comment by laradg** [comment]
Gerard agrees to the pagination solution:

Split the tables over different tabs:
-	Draft Cost items
-	To be Processed
-	Processed
-	Did not work

These tabs should have the same visibility/accessability as the tables do now for the different roles,
In addition:
- For a Professional, by default the Draft items tab should be opened
- For an Approver and for the Administrator, by default the To be Processed items tab should be opened

**Comment by davedx** [comment]
Sounds good. I'll tackle this one next if that's okay?

**Comment by laradg** [comment]
That would be great, thank you! xxxx

**Comment by davedx** [comment]
Done.

**Comment by laradg** [comment]
Pagination does not seem to work as expected.
First page, I see 10 entries. Click next page, I see 20 entries (different than the first 10). Click next page, I see 30 entries (different than the first 10+20).
Preferably, I would like to see 25 entries per page.

Filter does not work anymore now that pagination is introduced. I only see the timesheets of that person if they are present on the pagination page that I am looking at.

**Comment by laradg** [comment]
Works like a charm, thank you!
