### ISSUE TITLE
COPRA - Approver in tables [Cost items to be processed] and [Processed cost items]

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#47]
For CI's with status **Approved** or **Processed**, column Approver (highlighted below) should show the name of the actual Approver - whether this be the Approver, Backup approver, or one of the Admin users.

Technical details: We need two sets of "Approver" fields now:
  * Approver: this is what is displayed by default
  * Last approved by: this is updated whenever a timesheet is approved. If the field has a value, it is displayed instead of the primary approver field.

![image](https://user-images.githubusercontent.com/24442624/65433369-2a809b00-de1d-11e9-9d75-652bc87ee998.png)

![image](https://user-images.githubusercontent.com/24442624/65433413-3f5d2e80-de1d-11e9-8f2d-983972d3658c.png)

**Comment by laradg** [comment]
Follow up on issue #44

**Comment by davedx** [comment]
Cache in timesheet table on approve action

**Comment by laradg** [comment]
Tested but this is not working yet.
Approved a timesheet today, but the Approver column in the table is empty:

![image](https://user-images.githubusercontent.com/24442624/70044482-bef83e00-15c2-11ea-94ef-6d889d33f14e.png)

![image](https://user-images.githubusercontent.com/24442624/70044510-c91a3c80-15c2-11ea-9f9d-faf9fc83e05f.png)

**Comment by davedx** [comment]
Sigh, silly case issue. Fixed :)

**Comment by laradg** [comment]
Fixed for all newly approved timesheets
