### ISSUE TITLE
"Last day of the month" cut-off point does not create multiple CI's

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#50]
With a project that is set to cut-off point: "Last day of the month", in THIS week (including September 30th) only 1 CI is generated, showing all days of the week (including the days of the next month). This is incorrect.

What should happen is: 
2 CI's should be generated, 
* 1 for the days up until and including the last day of the month (only 30-09)
* another for all the days in the new month in this week (01-10 until 06-10)

**Comment by davedx** [comment]
Should be fixed now.
