### ISSUE TITLE
Filter on Status column in To be Processed Cost Items

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#51]
Question relates to section “Cost items to be processed”

 

Is there any possibility/plans to add sorting options to see items grouped base on Status ?

At the moment Filter timesheets is able to filter entries base on “Name” column
Is there possibility to filter also base on “Status” column.

On of above improvements could greatly help and optimize process of timesheet approvals, at least it could help team hiring manager side when tens of timesheet are waiting for processing, some are approved, some just submitted it is not convenient to navigate through long list of entries with mixed status to find which one is not yet approved and waits from action from my side  .

**Comment by davedx** [comment]
Added a dropdown to filter the different statuses in the "To be processed" view.
