### ISSUE TITLE
COPRA: Draft Cost item: KM/expenses deductible/reimbursed and Paid leave

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#53]
Follow up on issue #42 .

Change the view for Draft CI to show relevant fields KM/Expenses Reimbursed/Deductible and Paid leave, when relevant:

As per design below:
* Replace current field "Expenses €” by “Reimbursable expenses (€)” and display if applicable
* Add new field "Reimbursable travel (km)" and display if applicable
* Add new field "Paid leave" and display if applicable. If field "Hours worked" displays as a dropdown (units = days), then Paid leave should do the same. If field "Hours worked" displays as a text field (units = hours), then Paid leave should do the same.
* Add new field "Deductible travel expenses* (€)" and display if applicable
* Add new field "Other deductible expenses* (€)" and display if applicable
* Rename current field "Travel (km)” by “Deductible travel (KM)” and display if applicable 
* Display remark “Please submit your receipts to brigit@compasnl.com” at the bottom of the table if applicable (only if fields "Deductible travel expenses" and/or "Other deductible expenses" are visible)
* There is a slight separation in the design between the section ending with "Reimbursable travel" and the section start with "Paid leave". This is intentional to avoid erroneous data entry.

For the information sections marked with the following symbol: ![image](https://user-images.githubusercontent.com/24442624/66763725-a7e17d80-eea8-11e9-8677-17a4d7f6143d.png) (https://www.freeiconspng.com/img/6055)
Please include the following information on mouseover of the symbol for the respective fields:
[Reimbursable expenses]: Expenses that the endclient has accepted for reimbursement by the endclient
[Reimbursable travel (km)]: Driven kilometres that the endclient has accepted for reimbursement by the endclient
[Deductible travel expenses]: All work related travel expenses that are not reimbursed by the endclient (home-office, visit to home country, etc)
[Deductible travel (km)]: All work related driven kilometers that are not reimbursed by the endclient (home-office, etc) 
[Other deductible expenses]: All other work/profession related expenses that are not reimbursed by the endclient

![image](https://user-images.githubusercontent.com/24442624/66763486-2ee22600-eea8-11e9-826d-04383eb6dd14.png)

**Comment by davedx** [comment]
Important note: currently the cost items store the *reimbursable travel* in the "travel" column, and the *deductible travel* in the "travelDeductible" column of the TimesheetDays table.

**Comment by laradg** [comment]
Tested perfectly!
