### ISSUE TITLE
COPRA: Cost item beyond status Draft for Professional and Administrator - KM/expenses deductible/reimbursed and Paid leave

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#55]
Follow-up on issue #42 

![image](https://user-images.githubusercontent.com/24442624/66764169-7e752180-eea9-11e9-933d-2efba6c8b403.png)

Change the view for CI's after status Draft to show relevant fields KM/Expenses Reimbursed/Deductible and Paid leave (for Professional and Administrator), when relevant:

As per design:

* Replace current field "Expenses €” by “Reimbursable expenses (€)” and display if applicable
* Add new field "Reimbursable travel (km)" and display if applicable
* Add new field "Paid leave" and display if applicable. If field "Hours worked" displays as a dropdown (units = days), then Paid leave should do the same. If field "Hours worked" displays as a text field (units = hours), then Paid leave should do the same.
* Add new field "Deductible travel expenses* (€)" and display if applicable
* Add new field "Other deductible expenses* (€)" and display if applicable
* Rename current field "Travel (km)” by “Deductible travel (KM)” and display if applicable
* Display remark "* Please submit your receipts to brigit@compasnl.com"at the bottom of the table if applicable (only if fields "Deductible travel expenses" and/or "Other deductible expenses" are visible)
* There is a slight separation in the design between the section ending with "Reimbursable travel" and the section start with "Paid leave". This is intentional to avoid erroneous data entry.

**Comment by davedx** [comment]
I think this is the same behaviour as for the other fields (that they become disabled when they leave draft) -- if so then this is also ready to test.

**Comment by laradg** [comment]
Perfectly tested!
