### ISSUE TITLE
AVT - New export file for Payroll partner

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#58]
See attachment
[Sample of ComPas#.xlsx](https://github.com/laradg/copra-todo/files/3751614/Sample.of.ComPas.xlsx)
[Change Request - data export for ComPas.docx](https://github.com/laradg/copra-todo/files/3751616/Change.Request.-.data.export.for.ComPas.docx)

**Comment by laradg** [comment]
Outstanding questions:
- What is the correct date notation: "dd-mm-yy" or other?
- Should one file be generated per month, or may data of multiple months be included in one file?

**Comment by laradg** [comment]
What is the correct date notation: "dd-mm-yy" or other? **"dd-mm-yyyy"**
Should one file be generated per month, or may data of multiple months be included in one file? **Multiple months may be included in 1 file**

**Comment by davedx** [comment]
Closing this, please make a new issue when the new requirements are ready :)
