### ISSUE TITLE
COPRA: Sort functionality

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#59]
We would like to add sorting functionality to COPRA tables (only one sort can be active) on the end date column.
Default sort on this column would be preferred from old to new.

**Comment by davedx** [comment]
At the moment timesheets are sorted by startDate descending. For this feature, do we want to *add* sorting to the endDate in addition to startDate, or just make it so ascending/descending is toggleable on only the endDate column?

**Comment by laradg** [comment]
Make it so ascending/descending is toggleable on only the endDate column, please.

**Comment by laradg** [comment]
Functionality is working perfectly! :)
Just to check; the toggleable column header shows a square symbol behind Ends. Not sure whether that was the intention, or whether a symbol is not being shown properly here?

![image](https://user-images.githubusercontent.com/24442624/73162466-24ae0580-40ee-11ea-9b4d-3938a1310855.png)
