### ISSUE TITLE
Reject e-mails - send copy to backoffice@magno-it.nl

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#60]
**Could a copy of the Reject timesheet e-mail be sent to backoffice@magno-it.nl?**

Currently we Reject timesheets when contractors have made a mistake in their registration. The contractor is informed of this by an automatic e-mail and therefore has a chance to resubmit the timesheet.

In practice we have seen that this is sometimes forgotten by the contractor, or they miss the e-mail with the rejection. We currently do not have a system to monitor which timesheets we have rejected. If we could receive a copy of the rejection e-mail, then we can keep track of this until the timesheet has been resubmitted, or correct it ourselves if this takes too long.

**Comment by davedx** [comment]
I can definitely do this. If you want (in addition to this or instead of this), I could also build a new tab that shows any timesheets that have a "Rejected" action in their action history?

**Comment by laradg** [comment]
Yeah, that would be nice. Would that also be available for the contractor themselves?

**Comment by davedx** [comment]
Sure, it's easy to show or hide tabs for different roles.

**Comment by laradg** [comment]
Sorry, now that I have read your comment again, I see this is not the solution I would opt for.

I could also build a new tab that shows **any timesheets that have a "Rejected" action in their action history**?

If we were to make such a tab, only timesheets that have a "Rejected"action in their action history **AND** have status Draft should be on this tab (after all, the user should be able to change & resubmit the timesheet).
However, let's park this feature for now, as I believe Gerard would prefer to indicate the "Rejected" status of the timesheet in the current "Draft timesheets" table.

Issue is therefore still and only: **Could a copy of the Reject timesheet e-mail be sent to backoffice@magno-it.nl?**

**Comment by davedx** [comment]
Okay no problem, that's definitely the most simple solution too, let's do that. :)

**Comment by davedx** [comment]
Okay, reject emails are now also sent to backoffice with the subject like "COPRA Timesheet Rejected for Dave Clayton"

**Comment by laradg** [comment]
Tested successfully
