### ISSUE TITLE
COPRA mailer displays incorrect dates on mail message

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#64]
See below:

![image](https://user-images.githubusercontent.com/24442624/67773036-5c5bd180-fa5b-11e9-8336-0fe7cdf67408.png)

**Comment by davedx** [comment]
Erk. I know what caused this. :/ Will fix it tonight!

**Comment by laradg** [comment]
No problem, thanks for looking into it! xx

**Comment by laradg** [comment]
Tested, works correctly again! :)
