### ISSUE TITLE
Allow 2 decimal places for worked hours in Timesheets COPRA

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#67]
Due to a new client, where worked hours are registered in 2 decimal places (eg 8,75), we would like this to be possible in COPRA too.

Working day registration and DB are already correct, but frontend currently limits working hour registration to 1 decimal place. Please make this 2 decimal places.

**Comment by davedx** [comment]
Done.

**Comment by laradg** [comment]
Tested successfully
