### ISSUE TITLE
AVMT - Rename and replace

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#69]
![image](https://user-images.githubusercontent.com/24442624/73547150-abd8e180-443e-11ea-858c-b88a7b52b9c0.png)

1. Rename the tool "Accountview Management Tool" to "COPRA Management Tool"
2. The "COPRA Management Tool" should be directly accessible from Intranet (not by first going to AV Export tool)

**Comment by davedx** [comment]
1. is done, will do 2. when on the Windows laptop

**Comment by laradg** [comment]
Tested & approved
Ignore the replace, symbol could be confusing for other intranet users
