### ISSUE TITLE
Add Supplier field

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#70]
In case of a **Sales** project (below), add a selection field [Supplier] with choices: “ComPas”, “MIR” and “Other”. 
Add this field on a line between [Start date] and [Expenses Reimbursed].

Only show the following fields and make them mandatory if [Supplier]  has value "ComPas" or "MIR".
[Paid leave]
[Travel exp deductible]
[Other exp deductible]
[KM deductible]
[Max deductible travel] (see issue #74 )

If [Supplier] has value "Other" the above fields should be saved with value "No"
 
![image](https://user-images.githubusercontent.com/24442624/73549646-43403380-4443-11ea-98f1-b1c61bff4710.png)

**Comment by davedx** [comment]
Done
