### ISSUE TITLE
Add MaxDeductibleTravel field

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#74]
In case of a Sales project, add a text field [Max deductible travel] (float, positive number, 2 decimals).
Add this field at the end of the line of fields with [Travel exp deductible], [Other exp deductible], [KM deductible]

[Max deductible travel] should only be visible when Supplier = ComPas or MIR (see issue #70 )
If Supplier = "Other" then [Max deductible travel] should be saved with value NULL
This field is not mandatory

**Comment by davedx** [comment]
Done
