### ISSUE TITLE
Saving Purchase projects does not work

### ISSUE THREAD

**Issue by laradg** [laradg/copra-todo#82]
- Go to CMT (COPRA Management tool)
- Select a professional with a purchase project
- Open the purchase project
- Edit start and/or end date
- Save
- Close project

Date changes should be effective, but instead have not been saved.

EDIT: I cannot create and save a new Purchase project either

**Comment by laradg** [comment]
Server returned: message: "Cannot read property 'replace' of null"

**Comment by davedx** [comment]
I can't reproduce this locally using a recent copy of the (dev I think) database. Could you check production and see what's in the Migrations table to see if they've all been applied?

**Comment by laradg** [comment]
All scripts are in the Migration table, the AVProject table looks like this:
![image](https://user-images.githubusercontent.com/24442624/77053046-04077b00-69ce-11ea-96aa-f1440ca51a8c.png)

Perhaps I can test a new build of the Contracts/Intranet module to verify whether that changes anything?

**Comment by laradg** [comment]
Solved! \o/
